### PR TITLE
Ignore this, it's just a test

### PR DESCRIPTION
**Pull request by ndw**
I'm trying to work out why sometimes PR succeeds when it contains markup errors...

### CODE REVIEW

**Comment by ndw** [comment]
Right. So the challenge here is that this PR passes, even though one of the files is not schema-valid because PRs don't have access to a Saxon EE licensed processor. :-(

**Comment by ChristianGruen** [comment]
> Right. So the challenge here is that this PR passes, even though one of the files is not schema-valid because PRs don't have access to a Saxon EE licensed processor. :-(

Let’s hope there’ll be someone who can get hold of such licenses ;·) Well, I guess the problem is more technical.

**Comment by ndw** [comment]
Yes. The problem is that a PR doesn't usually have access to the CI "secrets" that include things like access tokens and, in this case, the Saxon EE license. That's because, in principle, a user could exfiltrate those secrets with a sufficiently devious PR.

In practice, we ignore build script and stylesheet changes in PRs, so I think it would be safe(ish) to allow PRs in this repository to have access to the secrets.  And that's probably what I'll do. After I check that the Saxon EE license we're using here has reasonable metadata and an expiration date!

**Comment by michaelhkay** [comment]
We have a mechanism that allows a compiled schema (SCM file) to contain an embedded key that enables validation against the schema to be done without a Saxon license, provided a master key was used when compiling the schema. Perhaps that would work here.

Michael Kay

**Comment by ndw** [comment]
I don't think there's an adequately secure way to do this. Bah, humbug.

It means we'll get occasional PRs that appear to pass bug cause failures when merged. I'll just deal with them when it happens until I'm sufficiently more frustrated to try to fix this some other way. (The obvious answer occurred to me this morning: convert the XSD files into RELAX NG and validate with those, but not today.)

**Pull request closed without merging**
