### PR TITLE
689 fn:stack-trace: replace with $err:stack-trace

### PR DESCRIPTION
**Pull request by ChristianGruen**
Issue: #689

### CODE REVIEW

**Comment by michaelhkay** [comment]
My concerns would be:

(a) a stack trace can be useful even if there is no error. It seems cumbersome having to raise and catch and error just to get a stack trace. 

(b) the way the information is being provided -- as a variable and as a map entry -- doesn't exactly make it easy for the implementation to construct and format the information lazily on demand. Providing it through a function is much more likely to be performant.

(c) XSLT 4.0 needs to be kept in sync.

**Comment by ChristianGruen** [comment]
> (a) a stack trace can be useful even if there is no error. It seems cumbersome having to raise and catch and error just to get a stack trace.

I followed the discussion in the issue, which resulted in a comment that it was consensus in Prague to remove the function (https://github.com/qt4cg/qtspecs/issues/689#issuecomment-2147376442).

> (b) the way the information is being provided -- as a variable and as a map entry -- doesn't exactly make it easy for the implementation to construct and format the information lazily on demand.

An alternative would be to return a function that returns the stack trace.

**Comment by michaelhkay** [comment]
I would be inclined to make it available (only) as a function within the map, so you do `$err:map?stack-trace()`.

**Comment by ChristianGruen** [comment]
Revised as discussed in [Meeting 094](https://qt4cg.org/meeting/minutes/2024/10-15.html); I kept `xs:string?` as return type.

**Comment by ndw** [comment]
The CG agreed to merge this issue at [meeting 098](https://qt4cg.org/meeting/minutes/2024/11-12.html).

**Pull request merged**
