### PR TITLE
868 fn:intersperse → fn:join, array:join($arrays, $separator)

### PR DESCRIPTION
**Pull request by ChristianGruen**
Issue: #868

### CODE REVIEW

**Comment by ChristianGruen** [comment]
> I'm not sure I understand the use case for making the second argument of string-join into a sequence.

It’s an alignment with intersperse/join; and I did not see a reason not to do it, as we already allow it to be an empty sequence.

**Comment by wendellpiez** [comment]
`fn:chain-sequence()` as an alternative name for `fn:join()` ?

**Comment by ChristianGruen** [comment]
I have done the following changes (Sorry for the repeated commits): 

* `fn:string-join`: reverted to accept at most one separator item.
* `fn:join`: renamed to `fn:sequence-join`
* `array:join`: Signature and equivalent XPath code changed to take charge of empty-sequence separators (thanks Reece).

**Review by michaelhkay — COMMENTED** [review]
The array:join function needs a changes section.

**Comment by ChristianGruen** [comment]
> The array:join function needs a changes section.

…added

**Comment by ndw** [comment]
The CG agreed to merge this PR at [meeting 096](https://qt4cg.org/meeting/minutes/2024/10-29.html).

**Pull request merged**
