### PR TITLE
361: Named arguments: $input vs. $value

### PR DESCRIPTION
**Pull request by ChristianGruen**
#361: Just an editorial one to get one more issue closed.

### CODE REVIEW

**Comment by ChristianGruen** [comment]
> In resolve-uri(), I'm not sure $uri is a good name for an argument that expects a relative URI reference. Technically, despite common usage, a relative reference is not a URI. Perhaps $href?

True, `$href` could be a viable alternative (I chose `$uri` because absolute URIs are legal inputs). I’ll change that.

**Comment by ChristianGruen** [comment]
(updated, can be merged)

**Comment by ndw** [comment]
The CG agreed to merge this PR at [meeting 040](https://qt4cg.org/meeting/minutes/2023/06-27.html).

**Comment by michaelhkay** [comment]
Unfortunately the stylesheet for generating the tests in misc-BuiltInKeywords used the parameter names as a hint for what value to generate, eg. if the parameter was named "json" then the value in the test case would be valid JSON. We're going to have to make it smarter.

**Pull request merged**
