### PR TITLE
1471 JSON Serialization: Sequences on Top Level

### PR DESCRIPTION
**Pull request by ChristianGruen**
Issue: #1471

### CODE REVIEW

**Comment by ChristianGruen** [comment]
…@ndw I re-committed all my PRs, but I guess there’s nothing I can do about the failing tests by myself?

**Comment by ndw** [comment]
Sorry about the PR build failure. Not your fault. I fixed it and reran the job.

**Comment by michaelhkay** [comment]
I'm not entirely convinced this is the right approach. If the user wants to output something that conforms to json-lines, this almost achieves it (using the default item-separator) except that an empty sequence is output as "null", rather than as an empty file. That glitch seems to be inviting trouble.

**Comment by ChristianGruen** [comment]
The PR will be revised and a new serialization parameter for [JSON Lines](https://jsonlines.org/) will be added.

**Comment by ChristianGruen** [comment]
Outdated; see #1497

**Pull request closed without merging**
