### PR TITLE
Revise the fn:parse-html rules to make them clearer to follow.

### PR DESCRIPTION
**Pull request by rhdunn**
This actions the comment in #767 that the rules for the function are unclear.

The SVG element name handling is correct in the spec per the comments in https://github.com/qt4cg/qt4tests/issues/57, so don't need changing.

### CODE REVIEW

**Review by ChristianGruen — APPROVED** [review]

**Comment by michaelhkay** [comment]
The spec still lacks a basic statement of what the function does: it's probably obvious that it parses HTML, but it doesn't actually say so. (It shouldn't rely on the summary, which should only summarise what is said in more detail in the Rules).

I suggest something like: "The function takes as input lexical HTML contained in the string or octet sequence supplied in the $html argument, and parses this to construct an XDM document node. Conceptually, this is done by parsing the HTML to construct a DOM representation following the rules in the relevant HTML specifications, and then converting the DOM to an XDM document node as described in section 15.6."

**Comment by rhdunn** [comment]
I'll add something similar to that to the rules. Note, though, that providing an overview of the behaviour of the function (repeating/rephrasing the summary) is not consistent across the specification, e.g. https://www.w3.org/TR/xpath-functions-31/#func-json-doc -- that does not have a sentence in the rules that it parses the JSON document at the specified resource location.

**Comment by ChristianGruen** [comment]
I agree with @rhdunn: It's often not easy to judge (by browsing through the existing function set) what's exactly expected to be contained in the summary and the rules, and what's supposed to be informal and formal.

On the other hand, I clearly see it would be time consuming to get the full XQFO specification unified. Maybe there are specific functions in the spec that we can regard as references for future additions?

**Comment by michaelhkay** [comment]
Section §1.5 of F&O describes the notation conventions. In particular: _The first section in the proforma is a short summary of what the function does. This is intended to be informative rather than normative._

The summary should not say anything that is not already said elsewhere; equally, it should describe the "normal" behaviour of the function and can ignore edge cases and error cases.

**Comment by rhdunn** [comment]
I've updated the element and attribute node-name rules to account for SVG and MathML case-sensitive local names as noted by @hsivonen.

**Comment by ndw** [comment]
The group agreed to merge this PR at [meeting 053](https://qt4cg.org/meeting/minutes/2023/11-07.html)

**Pull request merged**
