### PR TITLE
1019 XQFO: Unknown option parameters

### PR DESCRIPTION
**Pull request by ChristianGruen**
Issue: #1019

### CODE REVIEW

**Comment by michaelhkay** [comment]
Thinking about this further, I'm unconvinced. 

If someone uses `saxon:double-space="x" ` as a serialization parameter, and then runs the query under BaseX, do you really want to require the implementation to throw an error? This would have a number of consequences:

(a) queries that currently run successfully would now fail.

(b) an implementation is forced to look at all options supplied, not only those it cares about.

(c) portability even across different versions/variants of the same product would become more difficult.

While I agree that the change would ensure that misspellings are caught, I'm not sure that it's a net win.

**Comment by ChristianGruen** [comment]
If the proposed change seems to strict, we could change MUST to SHOULD or MAY (and thus make it completely implementation-defined):

> If an option is neither described in the specification nor supported by the implementation, a type error `FORG0013` SHOULD be raised.

**Comment by ChristianGruen** [comment]
As motivated by @ndw (thanks), I’ve rewritten the rules to clarify that only those unknown options that are in no namespace must be rejected.

@michaelhkay pointed out that we could use plausibility checks. I guess the general rules are described in [2.4.6 Implausible Expressions](https://qt4cg.org/specifications/xquery-40/xpath-40.html#id-implausible-expressions). I’ve sticked with the existing presentation, as I’m not sure how this would need to be incorporated into the text.

**Comment by ndw** [comment]
Looks good to me. I'm tempted to mark this as "merge without discussion" but in any event, I hope the discussion can be brief this time around :-)

**Comment by ndw** [comment]
The CG agreed to merge this PR at [meeting 071](https://qt4cg.org//meeting/minutes/2024/03-26.html)

**Pull request merged**
