### PR TITLE
Fix xnt references

### PR DESCRIPTION
**Pull request by ndw**
This PR doesn't make any technical changes[*]. It fixes some bugs in how cross-spec references are resolved. I failed to delete some out-of-date index files when I updated the code to generate them automatically. That lead to weird URIs. And I failed to update the stylesheets to correct for a change from `doc-xpath-` to `doc-xpath40` in the targets. Thanks to @michaelhkay for a detailed bug report.

[*] That's not 100% true, I did change to `<xterm>` references to `BracedURILiteral` into `<xnt>` references in `function-catalog.xml`.

### CODE REVIEW

**Comment by ndw** [comment]
I think @michaelhkay and I have both fixed the `BracedURILiteral` issue :-( so I'm going to let his merge go in first so fixing the merge conflict falls to me.

**Review by ChristianGruen — APPROVED** [review]

**Comment by rhdunn** [comment]
I'm still getting several build warnings and errors when running `./gradlew publish`, although several others have been fixed in this PR. (I've ommitted the tasks that have built without errors.):

```
> Task :xslt_grammar
Transforming specifications/xslt-40/src/xslt.xml...

        WARNING!! production with name="MapTest" not found


        WARNING!! production with name="ArrayTest" not found


        WARNING!! production with name="EnumerationType" not found


        WARNING!! production with name="NamedItemType" not found


> Task :xslt_merge_catalog
Transforming specifications/xslt-40/src/function-catalog.xml...
Checking internal links...
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to section  streamability-fn-replicate

> Task :fo_html
Function fn:foot in catalog but not spec
Function fn:parcel in catalog but not spec
Function fn:parts in catalog but not spec
Function fn:truncate in catalog but not spec
Function array:members in catalog but not spec
Function array:of in catalog but not spec
specdoc is FO40
Warning: no definition of function/operator: "numeric-greater-than" ()
Error: errorref RX0005 not found.
Warning: no definition of function/operator: "uniform" ()
Warning: no definition of function/operator: "unique" ()
Warning: no definition of function/operator: "A2S" ()
Warning: no definition of function/operator: "items-until" ()
Warning: no definition of function/operator: "items-from" ()
Warning: no definition of function/operator: "XX-equal" ()
Warning: no definition of function/operator: "XX-less-than" ()
Warning: no definition of function/operator: "XX-greater-than" ()
Warning: no definition of function/operator: "A2S" ()
Warning: no definition of function/operator: "S2A" ()

> Task :fo_html_diff
Function fn:foot in catalog but not spec
Function fn:parcel in catalog but not spec
Function fn:parts in catalog but not spec
Function fn:truncate in catalog but not spec
Function array:members in catalog but not spec
Function array:of in catalog but not spec
specdoc is FO40
Warning: no definition of function/operator: "numeric-greater-than" ()
Error: errorref RX0005 not found.
Warning: no definition of function/operator: "uniform" ()
Warning: no definition of function/operator: "unique" ()
Warning: no definition of function/operator: "A2S" ()
Warning: no definition of function/operator: "items-until" ()
Warning: no definition of function/operator: "items-from" ()
Warning: no definition of function/operator: "XX-equal" ()
Warning: no definition of function/operator: "XX-less-than" ()
Warning: no definition of function/operator: "XX-greater-than" ()
Warning: no definition of function/operator: "A2S" ()
Warning: no definition of function/operator: "S2A" ()

> Task :xquery_shared_html
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ContextItemDecl"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ParamList"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Param"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForMemberClause"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForMemberBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LetBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-PositionalArguments"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LocalNamespaceDecls"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LocalNamespaceDecl"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Prefix"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-AnyItemTest"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-AtomicOrUnionType"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-SimpleTypeName"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-PITarget"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-CharRef"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-NCName"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-S"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Char"

> Task :xquery_shared_html_diff
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ContextItemDecl"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ParamList"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Param"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForMemberClause"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForMemberBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LetBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-PositionalArguments"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LocalNamespaceDecls"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LocalNamespaceDecl"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Prefix"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-AnyItemTest"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-AtomicOrUnionType"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-SimpleTypeName"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-PITarget"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-CharRef"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-NCName"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-S"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Char"

> Task :xslt_html
Error: cannot resolve xtermref dt-function-name-resolver in XP40 at id=static-context
Error: cannot resolve xtermref dt-known-func-signatures in XP40 at id=static-context
Error: cannot resolve xtermref dt-function-name-resolver in XP40 at id=resolving-function-names
Error: cannot resolve xtermref dt-named-functions in XP40 at id=evaluation-context
Error: cannot resolve xnt nt-ItemType in XP40 at id=dt-type-pattern
Error: cannot resolve nt: prod-xslt40-patterns-FieldDeclaration
Error: cannot resolve nt: prod-xslt40-patterns-FieldDeclaration
Error: cannot resolve nt: prod-xslt40-patterns-ExtensibleFlag
Error: cannot resolve xtermref dt-named-functions in XP40 at id=evaluate-dynamic-context
Unsupported specref to  [streamability-fn-replicate]  (Contact stylesheet maintainer).
Error: cannot resolve xnt dt-EQName in XP40 at id=validation-xsl-type
Error: cannot resolve xnt nt-ItemType in XP40 at id=dt-type-pattern

> Task :xslt_html_diff
Error: cannot resolve xtermref dt-function-name-resolver in XP40 at id=static-context
Error: cannot resolve xtermref dt-known-func-signatures in XP40 at id=static-context
Error: cannot resolve xtermref dt-function-name-resolver in XP40 at id=resolving-function-names
Error: cannot resolve xtermref dt-named-functions in XP40 at id=evaluation-context
Error: cannot resolve xnt nt-ItemType in XP40 at id=dt-type-pattern
Error: cannot resolve nt: prod-xslt40-patterns-FieldDeclaration
Error: cannot resolve nt: prod-xslt40-patterns-FieldDeclaration
Error: cannot resolve nt: prod-xslt40-patterns-ExtensibleFlag
Error: cannot resolve xtermref dt-named-functions in XP40 at id=evaluate-dynamic-context
Unsupported specref to  [streamability-fn-replicate]  (Contact stylesheet maintainer).
Error: cannot resolve xnt doc-xpath40-AtomicOrUnionType in XP40 at id=NT-MapType
Error: cannot resolve xnt dt-EQName in XP40 at id=validation-xsl-type
Error: cannot resolve xnt nt-ItemType in XP40 at id=dt-type-pattern
```

**Comment by michaelhkay** [comment]
I'm seeing most of these warnings too (though not all). I think some are due to the fact that we haven't updated all spec="XP31" references to spec="XP40" style, but others may be content issues - perhaps in some cases due to one GIT branch referencing a term that's defined or renamed on a differen GIT branch. Don't worry too much about them for the moment.

It's unfortunate that F&O historically identifies links to functions as simply <code>fn:something</code> rather than <function>fn:something</function>, which means you can't write "<code>fn:unique</code has been renamed" withot getting a warning.

Michael Kay

On 21 Nov 2022, at 09:11, Reece H. Dunn ***@***.******@***.***>> wrote:



I'm still getting several build warnings and errors when running ./gradlew publish, although several others have been fixed in this PR. (I've ommitted the tasks that have built without errors.):

> Task :xslt_grammar
Transforming specifications/xslt-40/src/xslt.xml...

        WARNING!! production with name="MapTest" not found


        WARNING!! production with name="ArrayTest" not found


        WARNING!! production with name="EnumerationType" not found


        WARNING!! production with name="NamedItemType" not found


> Task :xslt_merge_catalog
Transforming specifications/xslt-40/src/function-catalog.xml...
Checking internal links...
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to section  streamability-fn-replicate

> Task :fo_html
Function fn:foot in catalog but not spec
Function fn:parcel in catalog but not spec
Function fn:parts in catalog but not spec
Function fn:truncate in catalog but not spec
Function array:members in catalog but not spec
Function array:of in catalog but not spec
specdoc is FO40
Warning: no definition of function/operator: "numeric-greater-than" ()
Error: errorref RX0005 not found.
Warning: no definition of function/operator: "uniform" ()
Warning: no definition of function/operator: "unique" ()
Warning: no definition of function/operator: "A2S" ()
Warning: no definition of function/operator: "items-until" ()
Warning: no definition of function/operator: "items-from" ()
Warning: no definition of function/operator: "XX-equal" ()
Warning: no definition of function/operator: "XX-less-than" ()
Warning: no definition of function/operator: "XX-greater-than" ()
Warning: no definition of function/operator: "A2S" ()
Warning: no definition of function/operator: "S2A" ()

> Task :fo_html_diff
Function fn:foot in catalog but not spec
Function fn:parcel in catalog but not spec
Function fn:parts in catalog but not spec
Function fn:truncate in catalog but not spec
Function array:members in catalog but not spec
Function array:of in catalog but not spec
specdoc is FO40
Warning: no definition of function/operator: "numeric-greater-than" ()
Error: errorref RX0005 not found.
Warning: no definition of function/operator: "uniform" ()
Warning: no definition of function/operator: "unique" ()
Warning: no definition of function/operator: "A2S" ()
Warning: no definition of function/operator: "items-until" ()
Warning: no definition of function/operator: "items-from" ()
Warning: no definition of function/operator: "XX-equal" ()
Warning: no definition of function/operator: "XX-less-than" ()
Warning: no definition of function/operator: "XX-greater-than" ()
Warning: no definition of function/operator: "A2S" ()
Warning: no definition of function/operator: "S2A" ()

> Task :xquery_shared_html
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ContextItemDecl"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ParamList"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Param"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForMemberClause"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForMemberBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LetBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-PositionalArguments"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LocalNamespaceDecls"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LocalNamespaceDecl"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Prefix"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-AnyItemTest"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-AtomicOrUnionType"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-SimpleTypeName"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-PITarget"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-CharRef"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-NCName"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-S"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Char"

> Task :xquery_shared_html_diff
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ContextItemDecl"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ParamList"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Param"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForMemberClause"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForMemberBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LetBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-PositionalArguments"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LocalNamespaceDecls"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LocalNamespaceDecl"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Prefix"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-AnyItemTest"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-AtomicOrUnionType"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-SimpleTypeName"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-PITarget"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-CharRef"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-NCName"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-S"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Char"

> Task :xslt_html
Error: cannot resolve xtermref dt-function-name-resolver in XP40 at id=static-context
Error: cannot resolve xtermref dt-known-func-signatures in XP40 at id=static-context
Error: cannot resolve xtermref dt-function-name-resolver in XP40 at id=resolving-function-names
Error: cannot resolve xtermref dt-named-functions in XP40 at id=evaluation-context
Error: cannot resolve xnt nt-ItemType in XP40 at id=dt-type-pattern
Error: cannot resolve nt: prod-xslt40-patterns-FieldDeclaration
Error: cannot resolve nt: prod-xslt40-patterns-FieldDeclaration
Error: cannot resolve nt: prod-xslt40-patterns-ExtensibleFlag
Error: cannot resolve xtermref dt-named-functions in XP40 at id=evaluate-dynamic-context
Unsupported specref to  [streamability-fn-replicate]  (Contact stylesheet maintainer).
Error: cannot resolve xnt dt-EQName in XP40 at id=validation-xsl-type
Error: cannot resolve xnt nt-ItemType in XP40 at id=dt-type-pattern

> Task :xslt_html_diff
Error: cannot resolve xtermref dt-function-name-resolver in XP40 at id=static-context
Error: cannot resolve xtermref dt-known-func-signatures in XP40 at id=static-context
Error: cannot resolve xtermref dt-function-name-resolver in XP40 at id=resolving-function-names
Error: cannot resolve xtermref dt-named-functions in XP40 at id=evaluation-context
Error: cannot resolve xnt nt-ItemType in XP40 at id=dt-type-pattern
Error: cannot resolve nt: prod-xslt40-patterns-FieldDeclaration
Error: cannot resolve nt: prod-xslt40-patterns-FieldDeclaration
Error: cannot resolve nt: prod-xslt40-patterns-ExtensibleFlag
Error: cannot resolve xtermref dt-named-functions in XP40 at id=evaluate-dynamic-context
Unsupported specref to  [streamability-fn-replicate]  (Contact stylesheet maintainer).
Error: cannot resolve xnt doc-xpath40-AtomicOrUnionType in XP40 at id=NT-MapType
Error: cannot resolve xnt dt-EQName in XP40 at id=validation-xsl-type
Error: cannot resolve xnt nt-ItemType in XP40 at id=dt-type-pattern

**Comment by ndw** [comment]
I can dig a little deeper, but I've been assuming that some of these warnings were expected in the sense that the work is still ongoing and maybe we haven't connected all the dots yet.

**Comment by michaelhkay** [comment]
I did a bit of work fixing a few of the link errors today, there are more to do. It's hard to know which are actual problems in the specs and which are limitations of the build machinery - I think we're slowly eliminating the latter, so can start to focus on the former.

Michael Kay

On 21 Nov 2022, at 09:11, Reece H. Dunn ***@***.******@***.***>> wrote:



I'm still getting several build warnings and errors when running ./gradlew publish, although several others have been fixed in this PR. (I've ommitted the tasks that have built without errors.):

> Task :xslt_grammar
Transforming specifications/xslt-40/src/xslt.xml...

        WARNING!! production with name="MapTest" not found


        WARNING!! production with name="ArrayTest" not found


        WARNING!! production with name="EnumerationType" not found


        WARNING!! production with name="NamedItemType" not found


> Task :xslt_merge_catalog
Transforming specifications/xslt-40/src/function-catalog.xml...
Checking internal links...
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to termdef  dt-arity
**** Dangling reference to section  streamability-fn-replicate

> Task :fo_html
Function fn:foot in catalog but not spec
Function fn:parcel in catalog but not spec
Function fn:parts in catalog but not spec
Function fn:truncate in catalog but not spec
Function array:members in catalog but not spec
Function array:of in catalog but not spec
specdoc is FO40
Warning: no definition of function/operator: "numeric-greater-than" ()
Error: errorref RX0005 not found.
Warning: no definition of function/operator: "uniform" ()
Warning: no definition of function/operator: "unique" ()
Warning: no definition of function/operator: "A2S" ()
Warning: no definition of function/operator: "items-until" ()
Warning: no definition of function/operator: "items-from" ()
Warning: no definition of function/operator: "XX-equal" ()
Warning: no definition of function/operator: "XX-less-than" ()
Warning: no definition of function/operator: "XX-greater-than" ()
Warning: no definition of function/operator: "A2S" ()
Warning: no definition of function/operator: "S2A" ()

> Task :fo_html_diff
Function fn:foot in catalog but not spec
Function fn:parcel in catalog but not spec
Function fn:parts in catalog but not spec
Function fn:truncate in catalog but not spec
Function array:members in catalog but not spec
Function array:of in catalog but not spec
specdoc is FO40
Warning: no definition of function/operator: "numeric-greater-than" ()
Error: errorref RX0005 not found.
Warning: no definition of function/operator: "uniform" ()
Warning: no definition of function/operator: "unique" ()
Warning: no definition of function/operator: "A2S" ()
Warning: no definition of function/operator: "items-until" ()
Warning: no definition of function/operator: "items-from" ()
Warning: no definition of function/operator: "XX-equal" ()
Warning: no definition of function/operator: "XX-less-than" ()
Warning: no definition of function/operator: "XX-greater-than" ()
Warning: no definition of function/operator: "A2S" ()
Warning: no definition of function/operator: "S2A" ()

> Task :xquery_shared_html
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ContextItemDecl"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ParamList"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Param"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForMemberClause"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForMemberBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LetBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-PositionalArguments"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LocalNamespaceDecls"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LocalNamespaceDecl"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Prefix"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-AnyItemTest"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-AtomicOrUnionType"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-SimpleTypeName"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-PITarget"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-CharRef"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-NCName"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-S"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Char"

> Task :xquery_shared_html_diff
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ContextItemDecl"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ParamList"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Param"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForMemberClause"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-ForMemberBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LetBinding"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-PositionalArguments"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LocalNamespaceDecls"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-LocalNamespaceDecl"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Prefix"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-AnyItemTest"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-AtomicOrUnionType"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-SimpleTypeName"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-PITarget"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-CharRef"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-NCName"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-S"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Char"

> Task :xslt_html
Error: cannot resolve xtermref dt-function-name-resolver in XP40 at id=static-context
Error: cannot resolve xtermref dt-known-func-signatures in XP40 at id=static-context
Error: cannot resolve xtermref dt-function-name-resolver in XP40 at id=resolving-function-names
Error: cannot resolve xtermref dt-named-functions in XP40 at id=evaluation-context
Error: cannot resolve xnt nt-ItemType in XP40 at id=dt-type-pattern
Error: cannot resolve nt: prod-xslt40-patterns-FieldDeclaration
Error: cannot resolve nt: prod-xslt40-patterns-FieldDeclaration
Error: cannot resolve nt: prod-xslt40-patterns-ExtensibleFlag
Error: cannot resolve xtermref dt-named-functions in XP40 at id=evaluate-dynamic-context
Unsupported specref to  [streamability-fn-replicate]  (Contact stylesheet maintainer).
Error: cannot resolve xnt dt-EQName in XP40 at id=validation-xsl-type
Error: cannot resolve xnt nt-ItemType in XP40 at id=dt-type-pattern

> Task :xslt_html_diff
Error: cannot resolve xtermref dt-function-name-resolver in XP40 at id=static-context
Error: cannot resolve xtermref dt-known-func-signatures in XP40 at id=static-context
Error: cannot resolve xtermref dt-function-name-resolver in XP40 at id=resolving-function-names
Error: cannot resolve xtermref dt-named-functions in XP40 at id=evaluation-context
Error: cannot resolve xnt nt-ItemType in XP40 at id=dt-type-pattern
Error: cannot resolve nt: prod-xslt40-patterns-FieldDeclaration
Error: cannot resolve nt: prod-xslt40-patterns-FieldDeclaration
Error: cannot resolve nt: prod-xslt40-patterns-ExtensibleFlag
Error: cannot resolve xtermref dt-named-functions in XP40 at id=evaluate-dynamic-context
Unsupported specref to  [streamability-fn-replicate]  (Contact stylesheet maintainer).
Error: cannot resolve xnt doc-xpath40-AtomicOrUnionType in XP40 at id=NT-MapType
Error: cannot resolve xnt dt-EQName in XP40 at id=validation-xsl-type
Error: cannot resolve xnt nt-ItemType in XP40 at id=dt-type-pattern

**Pull request merged**
