### PR TITLE
QT4CG-051-04/05: Reflected today's meeting editorial suggestions

### PR DESCRIPTION
**Pull request by dnovatchev**
All 3 editorial suggestions made in today's meeting are now reflected.

### CODE REVIEW

**Comment by dnovatchev** [comment]
@ndw, @michaelhkay 

I believe that all changes requested at today's meeting have been performed and this PR is ready to be merged.

Thank you!

**Comment by ChristianGruen** [comment]
Thanks, @dnovatchev. Some editorial notes:

* Changes from other commits seem to have been slipped into your pull request. You could do a `git rebase master` in yout local branch, followed by `git push --force` to mend this.
* I’ve prefixed the action id to the title of the pull request. Otherwise, if a PR refers to an existing issue, it’s best to prefix the issue number.
* To get rid of the newline in the examples, you’ll need to remove the whitespace in between `<eg><CDATA[`.

![image

* There are no fixed conventions on how to format code in the specification. In general, it’s recommended to repeat the variable names of the function signature, and to present self-contained code (i.e., a syntactically valid expression). That’s the reason why XQuery is used in other places; it could look as follows:

```xquery
declare function chain(
  $input     as item()*,
  $functions as function(*)*
) as item()* {
  fold-left($functions, $input, apply($f,
    if (function-arity($f) eq 1) then [ $x ]
    else if ($x instance of array(*)) then $x
    else array { $x }
  ))
};
```

The XPath solution could look as follows (it would need to stay incomplete as it has no `return` clause):

```xquery
let $apply := function($input, $function) {
  fn:apply($function,
    if (function-arity($function) eq 1) then [ $input ]
    else if ($input instance of array(*)) then $input
    else array { $input }
  )
}
let $chain := function($input as item()*, $functions as function(*)*) as item()* {
  fold-left(functions, $input, $apply)
}
```

**Review by ChristianGruen — COMMENTED** [review]
Thanks, @dnovatchev. Some editorial notes:

* Changes from other commits seem to have been slipped into your pull request. You could do a `git rebase master` in yout local branch, followed by `git push --force` to mend this.
* I’ve prefixed the action id to the title of the pull request. Otherwise, if a PR refers to an existing issue, it’s best to prefix the issue number.
* To get rid of the newline in the examples, you’ll need to remove the whitespace in between `<eg><CDATA[`.

![image

* There are no fixed conventions on how to format code in the specification. In general, it’s recommended to repeat the variable names of the function signature, and to present self-contained code (i.e., a syntactically valid expression). That’s the reason why XQuery is used in other places; it could look as follows:

```xquery
declare function chain(
  $input     as item()*,
  $functions as function(*)*
) as item()* {
  fold-left($functions, $input, apply($f,
    if (function-arity($f) eq 1) then [ $x ]
    else if ($x instance of array(*)) then $x
    else array { $x }
  ))
};
```

The XPath solution could look as follows (it would need to stay incomplete as it has no `return` clause):

```xquery
let $apply := function($input, $function) {
  fn:apply($function,
    if (function-arity($function) eq 1) then [ $input ]
    else if ($input instance of array(*)) then $input
    else array { $input }
  )
}
let $chain := function($input as item()*, $functions as function(*)*) as item()* {
  fold-left(functions, $input, $apply)
}
```

**Comment by dnovatchev** [comment]
@ChristianGruen Thanks for your guidance!

I performed all recommended steps and now I can see the changes at: https://qt4cg.org/pr/773/xpath-functions-40/Overview.html#func-chain

Thanks!

**Comment by ChristianGruen** [comment]
@dnovatchev Good to hear!

Something must have gone wrong, though, as various edits would be reverted by your PR: https://qt4cg.org/pr/773/xpath-functions-40/autodiff.html (try »View Only«).

Maybe you forgot to fetch the latest master branch and rebased an older version?

**Comment by dnovatchev** [comment]
> @dnovatchev Good to hear!
> 
> Something must have gone wrong, though, as various edits would be reverted by your PR: https://qt4cg.org/pr/773/xpath-functions-40/autodiff.html (try »View Only«).
> 
> Maybe you forgot to fetch the latest master branch and rebased an older version?

@ChristianGruen,
When trying to sync my branch with the qt4cg/qtspec Master, I get a message that "This branch is not behind the upstream qt4cg:master"

What am I doing wrong and what I should do?

image

**Pull request closed without merging**
