### PR TITLE
XQFO edits 5.4-5.6

### PR DESCRIPTION
**Pull request by Arithmeticus**
Light edits for consistency.

- Examples in `char()` have been reordered so that the most interesting and useful examples are at top.
- Substring functions were difficult to read in the specs because of the overly long collation URI. These are now bound to a variable, to enhance legibility.
- Schema location fixed.
- extra examples in `string-length()`, to help users recognize the role of combining characters.

### CODE REVIEW

**Review by ChristianGruen — APPROVED** [review]
Looks good.

Your edits always help me improve my English (even though I didn’t write the original texts).

**Comment by Arithmeticus** [comment]
Thanks, very kind of you @ChristianGruen

**Review by michaelhkay — CHANGES_REQUESTED** [review]
The change to `xsi:schema-location` looks wrong. This attribute must contain alternative namespace URIs and location URIs.

All other changes look fine.

**Comment by Arithmeticus** [comment]
Done. I misinterpreted the error message reported in Oxygen. For <xsd:assert> to work, fos.xsd needs to be changed to v. 1.1. I'll handle that in a separate PR.

**Review by ChristianGruen — APPROVED** [review]

**Comment by ndw** [comment]
The CG agreed to merge this PR at [meeting 052](https://qt4cg.org/meeting/minutes/2023/10-31.html)

**Pull request merged**
