### PR TITLE
[XPath] Support multiple clauses in ForExpr and LetExpr.

### PR DESCRIPTION
**Pull request by rhdunn**
This implements the proposal in issue #22 to support multiple clauses in XPath ForExpr and LetExpr, with both the grammar and specification text changes.

### CODE REVIEW

**Comment by rhdunn** [comment]
The build failure is an out of memory error:

**Review by michaelhkay — COMMENTED** [review]
Any reason you didn't define the syntax simply as

`ForExpression ::= (SimpleForClause)+ "return" ExprSingle`

Alternatively I think it could also be

`SimpleForClause  ::=  "for"  SimpleForBinding (("," | "for")  SimpleForBinding)*`

Emphasising that there's no semantic distinction between "for" and "," here.




  | SimpleForClause | ::= | "for"  SimpleForBinding (","  SimpleForBinding)*
-- | -- | -- | --

**Comment by rhdunn** [comment]
I simply forgot that `+` existed in EBNF when updating the grammar. I like your alternative proposal better as you are right about the lack of semantic distinction.

I'll update the grammar with your alternative syntax for this.

**Comment by rhdunn** [comment]
This needs to be:

    ForExpression ::= (SimpleForClause)+ "return" ExprSingle

to work with the `member` keyword being on the `SimpleForClause` instead of the `SimpleForBinding`. I've also added a comment on the issue about this.

**Comment by michaelhkay** [comment]
This is now superseded and can be closed with no further action.

**Pull request closed without merging**
