### PR TITLE
NW for MK: Items before, etc. (177)

### PR DESCRIPTION
**Pull request by ndw**
This PR is intended to be technically equivalent to #177.

I've reworked a series of MK commits so that they are independent; I fear we would wind up with merge conflicts otherwise and cleaning up the merge conflicts, without accidentally making some other change, seemed riskier than just teasing them apart and making them independent before we accept and merge them.

### CODE REVIEW

**Comment by cmsmcq** [comment]
I don't see the new functions (items-before etc.) here, in the F and O spec.

**Comment by ChristianGruen** [comment]
@cmsmcq

You find them via https://qt4cg.org/
The direct link is https://qt4cg.org/pr/199/xpath-functions-40/autodiff.html

**Comment by ndw** [comment]
Formatted versions of the specifications with this PR applied [are available](https://qt4cg.org/#pr-199)

**Comment by cmsmcq** [comment]
Looks good for the most part, but:

* In 16.2.9 fn:items-after, the last example has no call to items-after.  I would suspect the intention was to modify it so that it did have such a call, but I don't see analogues to this example in the other sections.

**Comment by ndw** [comment]
This PR was accepted [on 25 October at meeting 008](https://qt4cg.org/meeting/minutes/2022/10-25.html#pr-items-before)

**Pull request merged**
