### PR TITLE
Create a schema-for-xslt40.xsd file for the current draft spec.

### PR DESCRIPTION
**Pull request by rhdunn**
Note: schema-for-xslt30.xsd is still referenced by other source files, such as xslt-first-cut.xml, so it has not been removed.

### CODE REVIEW

**Comment by ChristianGruen** [comment]
Hi @rhdunn, the PR seems to conflict with the current master branch. Do you think it’s worth to resolve the conflicts, or is the pull reuqest outdated?

**Comment by rhdunn** [comment]
@ChristianGruen Thanks. Norm created a commit with the equivalent of the first commit. I've now cherry-picked the other commits on top of the master branch.

**Comment by ndw** [comment]
@michaelhkay has made changes to `schema-for-xslt40.xsd` recently. Is this PR now overtaken by events, or are there still changes that are necessary?

**Comment by ChristianGruen** [comment]
@michaelhkay @rhdunn Do we want to keep this PR?

**Comment by ndw** [comment]
I'm guessing that this PR has been overtaken by events. If more work needs to be done, feel free to reopen it, or open a new one.

**Comment by michaelhkay** [comment]
Yes, I think it has been overtaken. Note, there is also an RNG schema that hasn't been updated for 4.0.

**Pull request closed without merging**
