### PR TITLE
959 fn:unix-time

### LINKED ISSUE #959: Milliseconds ↔ xs:dayTimeDuration, Unix time ↔ xs:dateTime
We should extend the constructor functions to convert integers (millisecond, and the Unix time, starting from `1970-01-01T00:00:00Z`) to `xs:dayTimeDuration` and `xs:dateTime` instances…

```xquery
xs:dateTime(12345),
xs:dayTimeDuration(12345)
```

…and it should be possible to convert the values back to integers.

Related: https://docs.basex.org/wiki/Conversion_Module#Dates_and_Durations

### PR DESCRIPTION
**Pull request by ChristianGruen**
Closes #959

### CODE REVIEW

**Comment by michaelhkay** [comment]
I suggest following current-dateTime() by declaring the result type as xs:dateTimeStamp and including the paragraph

If the implementation supports data types from XSD 1.1 then the returned value will be an instance of xs:dateTimeStamp. Otherwise, the only guarantees are that it will be an instance of xs:dateTime and will have a timezone component.

**Comment by michaelhkay** [comment]
Perhaps there should be a citation to something like https://pubs.opengroup.org/onlinepubs/9699919799/functions/time.html that gives an official definition

Are you sure that the supplied calculation handles leap seconds correctly?

**Comment by ChristianGruen** [comment]
I'll be glad to incorporate the suggestions.

> Are you sure that the supplied calculation handles leap seconds correctly?

As far as I remember, Unix time does not account for leap seconds; it assumes that every day has 86,400 seconds. So I would say that the presented calculation is correct, but I could add a note on this.

**Review by michaelhkay — CHANGES_REQUESTED** [review]
The examples suggest the intent that the returned value will always be in UTC timezone, but this is not stated in the rules.

**Comment by ChristianGruen** [comment]
> The examples suggest the intent that the returned value will always be in UTC timezone, but this is not stated in the rules.

:+1: I’ve added UTC timezone in the rules.

**Pull request merged**
