### PR TITLE
Edits to parse-uri()

### PR DESCRIPTION
**Pull request by Arithmeticus**
Attn @ndw -- these edits pertain to 6.6.1 `fn:parse-uri` and require your careful review.

- `hierarchical` option appears in the rules of the function but not its preamble
- "This function is described..." moved to anticipate the actual narrative. 
- I was a bit thrown by the phrase "This approach...is not implementation advice" because "approach" is vague and the reader is left with the impression that a good deal of _something_ that follows is non-normative. We offer non-normative prose in the rules, but that informal prose is normally followed by an equivalent description that _is_ normative. I did not make any edits in this area, but I would recommend clarification as to exactly what parts of the narrative are normative and which are non-normative.
- The period-to-colon change at 27573 is to make sure the reader remains aware of the governing "If..." clause.
- I deleted a paragraph that attempted to distill the rather complicated description of `fn:decode-from-uri`. A mere xref provides a cleaner narrative here and a more accurate description of uri decoding, and the xref is within the same document, so should not pose a burden on the reader.
- For the `query-parameters` there was a discrepancy in the data model presented (in the preamble versus in the function rules), and I opted for the array-of-maps model. If it's supposed to be the other way (simple map), let me know and I'll revise.
- `query-segments` versus `query-parameters`; I went with the latter.

Let me know where things ain't right.

### CODE REVIEW

**Comment by ChristianGruen** [comment]
@Arithmeticus Thanks for the edits. Note that there’s another pull requests for `fn:parse-uri` that we should probably merge first: #770. Some of your suggestions seem to have been covered in both PRs.

**Comment by Arithmeticus** [comment]
Thanks, yes, there's some overlap. Once that PR is dealt with, I'll rebase the branch behind this PR and tidy up, and re-summarize what needs to be looked at.

**Comment by Arithmeticus** [comment]
Revised in light of today's merge-ment. See new commit. The fifth and sixth bullet points in my cover message no longer apply.

**Review by ChristianGruen — APPROVED** [review]

**Comment by ndw** [comment]
I will happily, and with gratitude, accept all of these proposed changes.

**Comment by ndw** [comment]
The group agreed to merge this PR at [meeting 053](https://qt4cg.org/meeting/minutes/2023/11-07.html)

**Pull request merged**
