### PR TITLE
434: Added examples for parse-integer()

### PR DESCRIPTION
**Pull request by Arithmeticus**
Supplemental examples related to pr #434 .

### CODE REVIEW

**Comment by michaelhkay** [comment]
I'm not sure of the rationale for some of these changes, which go well beyond adding examples.

- The ability to include underscores in the string has been dropped
- There is no longer a clear statement that there must be at least one digit
- The indication that the upper-case equivalents of a-z are A-Z (which I added in response to a comment from MSpMcQ stating that this couldn't be taken for granted) has disappeared.

I'm actually wondering if the text (other than examples) has accidentally reverted to a previous draft?

**Comment by ndw** [comment]
That diff markup version does look weird. Consequence of other accepted PRs, I think. The diffs are supposed to be against the version that was the source of the fork, but that certainly doesn't look like what's going on here. The actual PR diff is just a single hexavigesimal example.

**Comment by Arithmeticus** [comment]
PR 462 was intended to be some simple supplements to what was, at the time, the main/master trunk. So any loss of text is due to version conflict.

Please advise on how to avoid this in the future.

**Comment by ChristianGruen** [comment]
> Please advise on how to avoid this in the future.

It might help to invoke `git rebase master` (and to hope that there won't be any conflicts).

**Comment by gimsieke** [comment]
Ah, the magic incantations of the early 21st century.

**Comment by ndw** [comment]
You could try rebasing on the current master and pushing it again. But I don't think this is your fault. I'm a little perplexed about how this happened, but it's in the build tools, not your PR.

**Pull request merged**
