### PR TITLE
517: fn:chain

### PR DESCRIPTION
**Pull request by dnovatchev**
I added fn:chain, which has been discussed in https://github.com/qt4cg/qtspecs/issues/517

### CODE REVIEW

**Comment by ChristianGruen** [comment]
@dnovatchev Thanks, and congrats for finalizing the PR. You may need to store the function-catalog.xml file with Unix-style newlines (\n), otherwise the diff cannot be properly displayed:

https://github.com/qt4cg/qtspecs/pull/733/files#diff-7625c07ae8131ff65c3caa677b188ed2b9b66237312d11c05a2fa2838c6f5c67

**Comment by dnovatchev** [comment]
Hi Christian,

> You may need to store the function-catalog.xml file with Unix-style
newlines (\n), otherwise the diff cannot be properly displayed

How to do this? Never needed to do this before.

Thanks,
Dimitre

**Comment by dnovatchev** [comment]
The line endings are now Unix style.

**Comment by ChristianGruen** [comment]
> How to do this? Never needed to do this before.

It depends on the text editor you use (many allow you to choose the line ending). Feel free to give us more information on your setup.

**Comment by dnovatchev** [comment]
This is now fixed

**Comment by ChristianGruen** [comment]
> This is now fixed

I don't think so: https://github.com/qt4cg/qtspecs/pull/733/files#diff-7625c07ae8131ff65c3caa677b188ed2b9b66237312d11c05a2fa2838c6f5c67

Maybe you haven't committed your changes yet?

**Comment by ChristianGruen** [comment]
You can also change your git configuration to always send `\n` (text eol=lf):

https://docs.github.com/de/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by dnovatchev** [comment]
Have patience: "build-pr / build-and-deploy-pr (pull_request_target)  n progress — This check has started..."   😄

**Comment by dnovatchev** [comment]
The latest changes must be there now.

**Comment by ChristianGruen** [comment]
Same as before, Dimitre:

gh

**Comment by michaelhkay** [comment]
I suggest using `$functions` rather than `$funSequence` as the argument keyword. We don't normally use camel-case except where XSD uses it.

I'm reading the rendered version of the new spec linked from the dashboard page. On this the "more formally" XPath code appears to be incomplete - it ends in a comma.

I'm not comfortable with logic reading `if(not($x instance of array(*))) then array{$x} else $x`. This seems to break substitutability. We've generally taken the view that if something works on items in general then it shouldn't treat arrays specially. Also there doesn't seem to be any equivalent in the "informal" exposition. If we had a general approach of treating arrays differently then this might make sense, but the function library should try and follow common conventions throughout.

Generally I think it would be simpler if we confined this to functions of arity one. Or perhaps we could devise a general mechanism, a function `fn:singularize` (for want of a better name) that takes a function of arity N as input and converts it to a function of arity 1 that takes an array as its single argument?

In Note 4, I suspect this should be a type error rather than a dynamic error. Rather than saying "It is a dynamic|type error", which is a phrase we often use for a normative statement, it might be worth using different phrasing to indicate that here we are only telling the reader something they could have worked out from the normative rules, perhaps "A consequence of the rules given earler is that a type error occurs if...".

There is markup available for declaring variables that are used in examples. It's necessary to use this markup to ensure that the examples are testable; at the moment the examples will generate test cases that fail with static errors due to undeclared variables. I can help with this if necessary.

**Comment by dnovatchev** [comment]
Christian,

I have done everything on my side:

1. Updated the 2 files.
2. Committed and pushed to (my fork's master branch)
3. Initiated a PR from my fork (master) to qtspecs (master)
4. The associated github actions/jobs completed successfully

image

So, what could be the issue?

**Comment by ChristianGruen** [comment]
> So, what could be the issue?

https://github.com/qt4cg/qtspecs/pull/733#issuecomment-1741686976

**Comment by dnovatchev** [comment]
Maybe this????


image

**Comment by ChristianGruen** [comment]
> Not sure how to avoid this from happening . Line endings have never been a problem for me before.

https://github.com/qt4cg/qtspecs/pull/733#issuecomment-1741821436

**Comment by michaelhkay** [comment]
Labelling as abandoned - superseded by #734

**Pull request closed without merging**
